###########
# site.title

title:    'BarnyardBot'
subtitle: 'Automating the barnyard resource harvesting process with Malmo'


#########################
# more settings

markdown: kramdown

exclude:
- README.md
- LICENSE.md
